this.workbox=this.workbox||{},this.workbox.core=function(exports){"use strict"
function e(e,r){const t=new URL(e)
for(const e of r)t.searchParams.delete(e)
return t.href}function r(){if(void 0===h){const e=new Response("")
if("body"in e)try{new Response(e.body),h=!0}catch(e){h=!1}h=!1}return h}function t(e){return new Promise((r=>setTimeout(r,e)))}try{self["workbox:core:7.0.0"]&&_()}catch(e){}const a=(()=>{"__WB_DISABLE_DEV_LOGS"in globalThis||(self.__WB_DISABLE_DEV_LOGS=!1)
let e=!1
const r={debug:"#7f8c8d",log:"#2ecc71",warn:"#f39c12",error:"#c0392b",groupCollapsed:"#3498db",groupEnd:null},t=function(t,a){if(self.__WB_DISABLE_DEV_LOGS)return
if("groupCollapsed"===t&&/^((?!chrome|android).)*safari/i.test(navigator.userAgent))return void console[t](...a)
const n=e?[]:["%cworkbox",[`background: ${r[t]}`,"border-radius: 0.5em","color: white","font-weight: bold","padding: 2px 0.5em"].join(";")]
console[t](...n,...a),"groupCollapsed"===t&&(e=!0),"groupEnd"===t&&(e=!1)},a={},n=Object.keys(r)
for(const e of n){const r=e
a[r]=(...e)=>{t(r,e)}}return a})(),n={"invalid-value":({paramName:e,validValueDescription:r,value:t})=>{if(!e||!r)throw new Error("Unexpected input to 'invalid-value' error.")
return`The '${e}' parameter was given a value with an unexpected value. ${r} Received a value of ${JSON.stringify(t)}.`},"not-an-array":({moduleName:e,className:r,funcName:t,paramName:a})=>{if(!(e&&r&&t&&a))throw new Error("Unexpected input to 'not-an-array' error.")
return`The parameter '${a}' passed into '${e}.${r}.${t}()' must be an array.`},"incorrect-type":({expectedType:e,paramName:r,moduleName:t,className:a,funcName:n})=>{if(!(e&&r&&t&&n))throw new Error("Unexpected input to 'incorrect-type' error.")
return`The parameter '${r}' passed into '${t}.${a?`${a}.`:""}${n}()' must be of type ${e}.`},"incorrect-class":({expectedClassName:e,paramName:r,moduleName:t,className:a,funcName:n,isReturnValueProblem:o})=>{if(!e||!t||!n)throw new Error("Unexpected input to 'incorrect-class' error.")
const s=a?`${a}.`:""
return o?`The return value from '${t}.${s}${n}()' must be an instance of class ${e}.`:`The parameter '${r}' passed into '${t}.${s}${n}()' must be an instance of class ${e}.`},"missing-a-method":({expectedMethod:e,paramName:r,moduleName:t,className:a,funcName:n})=>{if(!(e&&r&&t&&a&&n))throw new Error("Unexpected input to 'missing-a-method' error.")
return`${t}.${a}.${n}() expected the '${r}' parameter to expose a '${e}' method.`},"add-to-cache-list-unexpected-type":({entry:e})=>`An unexpected entry was passed to 'workbox-precaching.PrecacheController.addToCacheList()' The entry '${JSON.stringify(e)}' isn't supported. You must supply an array of strings with one or more characters, objects with a url property or Request objects.`,"add-to-cache-list-conflicting-entries":({firstEntry:e,secondEntry:r})=>{if(!e||!r)throw new Error("Unexpected input to 'add-to-cache-list-duplicate-entries' error.")
return`Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL ${e} but different revision details. Workbox is unable to cache and version the asset correctly. Please remove one of the entries.`},"plugin-error-request-will-fetch":({thrownErrorMessage:e})=>{if(!e)throw new Error("Unexpected input to 'plugin-error-request-will-fetch', error.")
return`An error was thrown by a plugins 'requestWillFetch()' method. The thrown error message was: '${e}'.`},"invalid-cache-name":({cacheNameId:e,value:r})=>{if(!e)throw new Error("Expected a 'cacheNameId' for error 'invalid-cache-name'")
return`You must provide a name containing at least one character for setCacheDetails({${e}: '...'}). Received a value of '${JSON.stringify(r)}'`},"unregister-route-but-not-found-with-method":({method:e})=>{if(!e)throw new Error("Unexpected input to 'unregister-route-but-not-found-with-method' error.")
return`The route you're trying to unregister was not  previously registered for the method type '${e}'.`},"unregister-route-route-not-registered":()=>"The route you're trying to unregister was not previously registered.","queue-replay-failed":({name:e})=>`Replaying the background sync queue '${e}' failed.`,"duplicate-queue-name":({name:e})=>`The Queue name '${e}' is already being used. All instances of backgroundSync.Queue must be given unique names.`,"expired-test-without-max-age":({methodName:e,paramName:r})=>`The '${e}()' method can only be used when the '${r}' is used in the constructor.`,"unsupported-route-type":({moduleName:e,className:r,funcName:t,paramName:a})=>`The supplied '${a}' parameter was an unsupported type. Please check the docs for ${e}.${r}.${t} for valid input types.`,"not-array-of-class":({value:e,expectedClass:r,moduleName:t,className:a,funcName:n,paramName:o})=>`The supplied '${o}' parameter must be an array of '${r}' objects. Received '${JSON.stringify(e)},'. Please check the call to ${t}.${a}.${n}() to fix the issue.`,"max-entries-or-age-required":({moduleName:e,className:r,funcName:t})=>`You must define either config.maxEntries or config.maxAgeSecondsin ${e}.${r}.${t}`,"statuses-or-headers-required":({moduleName:e,className:r,funcName:t})=>`You must define either config.statuses or config.headersin ${e}.${r}.${t}`,"invalid-string":({moduleName:e,funcName:r,paramName:t})=>{if(!t||!e||!r)throw new Error("Unexpected input to 'invalid-string' error.")
return`When using strings, the '${t}' parameter must start with 'http' (for cross-origin matches) or '/' (for same-origin matches). Please see the docs for ${e}.${r}() for more info.`},"channel-name-required":()=>"You must provide a channelName to construct a BroadcastCacheUpdate instance.","invalid-responses-are-same-args":()=>"The arguments passed into responsesAreSame() appear to be invalid. Please ensure valid Responses are used.","expire-custom-caches-only":()=>"You must provide a 'cacheName' property when using the expiration plugin with a runtime caching strategy.","unit-must-be-bytes":({normalizedRangeHeader:e})=>{if(!e)throw new Error("Unexpected input to 'unit-must-be-bytes' error.")
return`The 'unit' portion of the Range header must be set to 'bytes'. The Range header provided was "${e}"`},"single-range-only":({normalizedRangeHeader:e})=>{if(!e)throw new Error("Unexpected input to 'single-range-only' error.")
return`Multiple ranges are not supported. Please use a  single start value, and optional end value. The Range header provided was "${e}"`},"invalid-range-values":({normalizedRangeHeader:e})=>{if(!e)throw new Error("Unexpected input to 'invalid-range-values' error.")
return`The Range header is missing both start and end values. At least one of those values is needed. The Range header provided was "${e}"`},"no-range-header":()=>"No Range header was found in the Request provided.","range-not-satisfiable":({size:e,start:r,end:t})=>`The start (${r}) and end (${t}) values in the Range are not satisfiable by the cached response, which is ${e} bytes.`,"attempt-to-cache-non-get-request":({url:e,method:r})=>`Unable to cache '${e}' because it is a '${r}' request and only 'GET' requests can be cached.`,"cache-put-with-no-response":({url:e})=>`There was an attempt to cache '${e}' but the response was not defined.`,"no-response":({url:e,error:r})=>{let t=`The strategy could not generate a response for '${e}'.`
return r&&(t+=` The underlying error is ${r}.`),t},"bad-precaching-response":({url:e,status:r})=>`The precaching request for '${e}' failed`+(r?` with an HTTP status of ${r}.`:"."),"non-precached-url":({url:e})=>`createHandlerBoundToURL('${e}') was called, but that URL is not precached. Please pass in a URL that is precached instead.`,"add-to-cache-list-conflicting-integrities":({url:e})=>`Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL ${e} with different integrity values. Please remove one of them.`,"missing-precache-entry":({cacheName:e,url:r})=>`Unable to find a precached response in ${e} for ${r}.`,"cross-origin-copy-response":({origin:e})=>`workbox-core.copyResponse() can only be used with same-origin responses. It was passed a response with origin ${e}.`,"opaque-streams-source":({type:e})=>{const r=`One of the workbox-streams sources resulted in an '${e}' response.`
return"opaqueredirect"===e?`${r} Please do not use a navigation request that results in a redirect as a source.`:`${r} Please ensure your sources are CORS-enabled.`}}
class o extends Error{constructor(e,r){super(((e,r={})=>{const t=n[e]
if(!t)throw new Error(`Unable to find message for code '${e}'.`)
return t(r)})(e,r)),this.name=e,this.details=r}}const s={hasMethod:(e,r,t)=>{if("function"!=typeof e[r])throw t.expectedMethod=r,new o("missing-a-method",t)},isArray:(e,r)=>{if(!Array.isArray(e))throw new o("not-an-array",r)},isInstance:(e,r,t)=>{if(!(e instanceof r))throw t.expectedClassName=r.name,new o("incorrect-class",t)},isOneOf:(e,r,t)=>{if(!r.includes(e))throw t.validValueDescription=`Valid values are ${JSON.stringify(r)}.`,new o("invalid-value",t)},isType:(e,r,t)=>{if(typeof e!==r)throw t.expectedType=r,new o("incorrect-type",t)},isArrayOfClass:(e,r,t)=>{const a=new o("not-array-of-class",t)
if(!Array.isArray(e))throw a
for(const t of e)if(!(t instanceof r))throw a}},i=new Set,c={googleAnalytics:"googleAnalytics",precache:"precache-v2",prefix:"workbox",runtime:"runtime",suffix:"undefined"!=typeof registration?registration.scope:""},u=e=>[c.prefix,e,c.suffix].filter((e=>e&&e.length>0)).join("-"),l={updateDetails:e=>{(e=>{for(const r of Object.keys(c))e(r)})((r=>{"string"==typeof e[r]&&(c[r]=e[r])}))},getGoogleAnalyticsName:e=>e||u(c.googleAnalytics),getPrecacheName:e=>e||u(c.precache),getPrefix:()=>c.prefix,getRuntimeName:e=>e||u(c.runtime),getSuffix:()=>c.suffix}
let d,h
var p=Object.freeze({__proto__:null,assert:s,cacheMatchIgnoreParams:async function(r,t,a,n){const o=e(t.url,a)
if(t.url===o)return r.match(t,n)
const s=Object.assign(Object.assign({},n),{ignoreSearch:!0}),i=await r.keys(t,s)
for(const t of i)if(o===e(t.url,a))return r.match(t,n)},cacheNames:l,canConstructReadableStream:function(){if(void 0===d)try{new ReadableStream({start(){}}),d=!0}catch(e){d=!1}return d},canConstructResponseFromBodyStream:r,dontWaitFor:function(e){e.then((()=>{}))},Deferred:class{constructor(){this.promise=new Promise(((e,r)=>{this.resolve=e,this.reject=r}))}},executeQuotaErrorCallbacks:async function(){a.log(`About to run ${i.size} callbacks to clean up caches.`)
for(const e of i)await e(),a.log(e,"is complete.")
a.log("Finished running callbacks.")},getFriendlyURL:e=>new URL(String(e),location.href).href.replace(new RegExp(`^${location.origin}`),""),logger:a,resultingClientExists:async function(e){if(!e)return
let r=await self.clients.matchAll({type:"window"})
const a=new Set(r.map((e=>e.id)))
let n
const o=performance.now()
for(;performance.now()-o<2e3&&(r=await self.clients.matchAll({type:"window"}),n=r.find((r=>e?r.id===e:!a.has(r.id))),!n);)await t(100)
return n},timeout:t,waitUntil:function(e,r){const t=r()
return e.waitUntil(t),t},WorkboxError:o})
const m={get googleAnalytics(){return l.getGoogleAnalyticsName()},get precache(){return l.getPrecacheName()},get prefix(){return l.getPrefix()},get runtime(){return l.getRuntimeName()},get suffix(){return l.getSuffix()}}
return exports._private=p,exports.cacheNames=m,exports.clientsClaim=function(){self.addEventListener("activate",(()=>self.clients.claim()))},exports.copyResponse=async function(e,t){let a=null
if(e.url&&(a=new URL(e.url).origin),a!==self.location.origin)throw new o("cross-origin-copy-response",{origin:a})
const n=e.clone(),s={headers:new Headers(n.headers),status:n.status,statusText:n.statusText},i=t?t(s):s,c=r()?n.body:await n.blob()
return new Response(c,i)},exports.registerQuotaErrorCallback=function(e){s.isType(e,"function",{moduleName:"workbox-core",funcName:"register",paramName:"callback"}),i.add(e),a.log("Registered a callback to respond to quota errors.",e)},exports.setCacheNameDetails=function(e){if(Object.keys(e).forEach((r=>{s.isType(e[r],"string",{moduleName:"workbox-core",funcName:"setCacheNameDetails",paramName:`details.${r}`})})),"precache"in e&&0===e.precache.length)throw new o("invalid-cache-name",{cacheNameId:"precache",value:e.precache})
if("runtime"in e&&0===e.runtime.length)throw new o("invalid-cache-name",{cacheNameId:"runtime",value:e.runtime})
if("googleAnalytics"in e&&0===e.googleAnalytics.length)throw new o("invalid-cache-name",{cacheNameId:"googleAnalytics",value:e.googleAnalytics})
l.updateDetails(e)},exports.skipWaiting=function(){a.warn("skipWaiting() from workbox-core is no longer recommended and will be removed in Workbox v7. Using self.skipWaiting() instead is equivalent."),self.skipWaiting()},exports}({})
